name: Stop Vercel Project

on:
  schedule:
    - cron: "0 18 * * 1-5"

jobs:
  stop-project:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install Vercel CLI
        working-directory: ./agile-team-poker-backend
        run: npm install -g vercel

      - name: Remove Vercel project
        working-directory: ./agile-team-poker-backend
        run: vercel remove agile-team-poker-backend --token=${{ secrets.VERCEL_TOKEN }} -y
