name: Deploy Vercel Project

on:
  schedule:
    - cron: "0 7 * * 1-5"

jobs:
  deploy-project:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Create Firebase service account file
        working-directory: agile-team-poker-backend
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccount.json

      - name: Install Vercel CLI
        working-directory: agile-team-poker-backend
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: agile-team-poker-backend
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} -y
